# -*- mode: ruby -*-
# vi: set ft=ruby :

# VM private network (default: 192.168.250.35)
VGVM_PVTNET = ENV.key?('VGVM_PVTNET') ? ENV['VGVM_PVTNET'] : '192.168.250.35'

# VM memory on virtualbox (default: 1024MB)
VGVM_MEMORY = ENV.key?('VGVM_MEMORY') ? ENV['VGVM_MEMORY'] : 2048

# VM cpu/cores on virtualbox (default: 1 cpu/core)
VGVM_CPU = ENV.key?('VGVM_CPU') ? ENV['VGVM_CPU'] : 2

# Puppet/r10k Control repository to install from
VGVM_PP_CONTROL_REPO = ENV.key?('VGVM_PP_CONTROL_REPO') ?
                        ENV['VGVM_PP_CONTROL_REPO'] :
                       'https://github.com/puppet-br/pcp-controlrepo'

# vagrant-proxyconf: https://tmatilai.github.io/vagrant-proxyconf
# if necessary set OS environment variable PROXY|HTTP_PROXY|HTTPS_PROXY="http://proxy:port"
if ENV.key?('PROXY')
  HTTP_PROXY=ENV['PROXY']
elsif ENV.key?('proxy')
  HTTP_PROXY=ENV['proxy']
else
  print Vagrant.has_plugin?("vagrant-proxyconf") ?
          "WARN: you installed vagrant-proxyconf plugin, "+
          "but proxy environment variable (PROXY) not set yet!\n\n" : ''

  HTTP_PROXY="http://proxy_not_set:3128"
end
HTTPS_PROXY=HTTP_PROXY

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf") &&
      (HTTP_PROXY != "http://proxy_not_set:3128") # proxy settings
    config.proxy.http     = HTTP_PROXY
    config.proxy.https    = HTTPS_PROXY
    config.proxy.no_proxy = "localhost, 127.0.0.1, .hacklab"
    print "proxy settings: \n"
    print " - proxy.http:  "+config.proxy.http+"\n"
    print " - proxy.https: "+config.proxy.https+"\n"
    print " - no_proxy: "+config.proxy.no_proxy+"\n\n"
  end # end proxy settings

  if Vagrant.has_plugin?("vagrant-hosts")
    config.vm.provision :hosts do |provisioner|
      provisioner.add_localhost_hostnames = false
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_host VGVM_PVTNET, ['puppet']
    end
  end

  config.vm.box = "puppetlabs/centos-7.2-64-puppet"
  config.vm.box_check_update = false

  # puppet server + puppet agent
  config.vm.define "puppetserver" do |puppetserver|
    puppetserver.vm.hostname = "puppet-pcpm.hacklab"
    puppetserver.vm.network :private_network, ip: VGVM_PVTNET
    puppetserver.hostsupdater.aliases = ["puppetboard.hacklab", "puppetexplorer.hacklab"]
    puppetserver.vm.provision "shell", path: "installer.sh", args: [VGVM_PP_CONTROL_REPO]
    puppetserver.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--cpus", VGVM_CPU ]
      v.customize [ "modifyvm", :id, "--memory", VGVM_MEMORY ]
      v.customize [ "modifyvm", :id, "--name", "puppet-pcpm.hacklab" ]
      v.customize [ "modifyvm", :id, "--groups", "/pcp" ]
    end
  end

end
